server:
#  노트북 포트
#  port: 8080
#  데스크탑 포트
  port: 9000
  shutdown: graceful

spring:
  application:
    name: jutopia
  profiles:
    active: local
    group:
      "local": "local"
      "prd": "prd"
  thymeleaf:
    prefix: classpath:templates/main
    suffix: .html
    cache: false
    check-template-location: true
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: true
  servlet:
    multipart:
      maxFileSize: 30MB # 파일 하나의 최대 크기
      maxRequestSize: 40MB  # 한 번에 최대 업로드 가능 용량

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    doc-expansion: none
    tags-sorter: alpha
    operations-sorter: method
  api-docs:
    groups:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: refresh

---

spring:
  config:
    activate:
      on-profile: "local"
    import:
      - classpath:config/local/config.yml
      - classpath:config/local/secret-config.yml
      - classpath:config/local/datasource.yml

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: info